monolog:
    handlers:
        prod-signaler:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE # this means that all message of level NOTICE or higher are always logged
            handler: main_syslog
            bubble: false # if we handle it, nothing else should
        main_syslog:
            type: stream
            path: "php://stderr"
            formatter: surfnet_stepup.monolog.json_formatter
            channels: "!event"

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: debug
                channels: "!event"
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation", "!console"]

when@test:
    monolog:
        handlers:
            main:
                path: php://stderr
                type: fingers_crossed
                passthru_level: NOTICE
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: "!event"
            nested:
                type: stream
                path: php://stderr
                level: debug
