version: '2.4'

services:
  tiqr.stepup.example.com:
    image: nginx:latest
    container_name: tiqr-nginx
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../public:/var/www/public
      - ../../ci/files/tiqr.stepup.example.com.crt:/etc/nginx/certs/tiqr.example.com.crt
      - ../../ci/files/tiqr.stepup.example.com.key:/etc/nginx/certs/tiqr.example.com.key
    ports:
      - 443:443
    depends_on:
      - app.tiqr.stepup.example.com

  app.tiqr.stepup.example.com:
    stdin_open: true
    image: ghcr.io/openconext/openconext-containers/openconext-php-test-stepup:latest
    user: "${UID}:${GID}"
    container_name: tiqr-test
    volumes:
      - ../../:/var/www/
