controllers:
    resource: ../src/Controller/
    type: attribute

gssp_saml:
    resource: '@SurfnetGsspBundle/Resources/config/routing.yml'

openconext_monitor:
    resource:   "@OpenConextMonitorBundle/Resources/config/routing.yml"
    prefix:     /
