# Install the "REMI" repo which contain newer php packages that override the default
# that come with the distro (CentOS7: 5.4; CentOS6: 5.3)
- name: Install REMI repo
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: Enable REMI repo
  copy: src=remi.repo dest=/etc/yum.repos.d/remi.repo

- name: Install common packages
  yum: name={{item}} state=present
  with_items:
  - vim
  - composer
  - git

- name: Install nginx, php-(cli,fpm)
  yum: name={{item}} state=present
  with_items:
  - nginx
  - php-fpm
  - php-gmp
  - php-cli
  - php-mbstring
  - php-mcrypt
  - php-intl
  - php-dom
  - php-xdebug
  - php-pecl-memcache

- name: Put php.ini
  template: src='php.ini.j2' dest='/etc/php.ini'
  notify:
    - restart php-fpm

- name: Put default xdebug config
  template: src='files/xdebug.ini' dest='/etc/php.d/xdebug.ini'
  notify:
    - restart php-fpm

# Remove default conf files
- name: Remove known default distro files in /etc/nginxconf.d/ and /etc/php-fpm.d/
  file: path={{item}} state=absent
  with_items:
  - /etc/php-fpm.d/www.conf
  - /etc/nginx/conf.d/default.conf
  - /etc/nginx/conf.d/ssl.conf
  - /etc/nginx/conf.d/virtual.conf
  notify:
  - restart nginx
  - restart php-fpm

# Install php and nginx conf files
- name: Put /etc/php-fpm.conf
  copy: src='files/php-fpm.conf' dest='/etc/php-fpm.conf'
  notify:
      - restart php-fpm

- name: Put nginx.conf
  template: src='nginx.conf.j2' dest='/etc/nginx/nginx.conf'
  notify:
      - restart nginx

- include: tasks/vhost.yml

# Because nginx will restart with an invalid config without service detecting this, so we test the config  first
- name: Test nginx config
  command: /sbin/nginx -t
  register: nginx_test
  changed_when: False
  failed_when: nginx_test.rc > 0

- name: Start and enable nginx & php-fpm
  service: name={{item}} state=started enabled=true
  with_items:
  - nginx
  - php-fpm

- name: Put rsyslog config for nginx
  copy: src=rsyslog_nginx.conf dest=/etc/rsyslog.d/nginx.conf
  notify: restart rsyslog

